// <auto-generated />
namespace Room_allocation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class user_details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_details));
        
        string IMigrationMetadata.Id
        {
            get { return "201807310006189_user_details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
