//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace event_management1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string email_id { get; set; }
        public string password { get; set; }
    }
}
