//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Operation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string Title { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public byte[] Duration { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public bool IsPublic { get; set; }
    }
}
