// <auto-generated />
namespace UserRegAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class userdetails2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userdetails2));
        
        string IMigrationMetadata.Id
        {
            get { return "201808220426468_userdetails2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
